using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Marketplace.Web.Modules.Catalog;
using Marketplace.Web.Modules.Listings;
using Marketplace.Web.Modules.Moderation;
using Marketplace.Web.Modules.Geo;
using Marketplace.Web.Modules.Messaging;
using Marketplace.Web.Modules.Engagement;
using Marketplace.Web.Modules.Recommendations;
using Marketplace.Web.Modules.Administration;
using Marketplace.Web.Modules.Monetization;

namespace Marketplace.Web.Modules.Identity;

public sealed class MarketplaceDbContext(DbContextOptions<MarketplaceDbContext> options)
    : IdentityDbContext<ApplicationUser, IdentityRole<Guid>, Guid>(options)
{
    public DbSet<UserSession> UserSessions => Set<UserSession>();
    public DbSet<AuditEvent> AuditEvents => Set<AuditEvent>();
    public DbSet<OneTimeCodeChallenge> OneTimeCodeChallenges => Set<OneTimeCodeChallenge>();
    public DbSet<AuthRateLimitBucket> AuthRateLimitBuckets => Set<AuthRateLimitBucket>();
    public DbSet<AccountErasureRequest> AccountErasureRequests => Set<AccountErasureRequest>();
    public DbSet<CatalogCategory> CatalogCategories => Set<CatalogCategory>();
    public DbSet<CategorySchemaVersion> CategorySchemaVersions => Set<CategorySchemaVersion>();
    public DbSet<CategoryAttribute> CategoryAttributes => Set<CategoryAttribute>();
    public DbSet<Listing> Listings => Set<Listing>();
    public DbSet<ListingRevision> ListingRevisions => Set<ListingRevision>();
    public DbSet<ListingMedia> ListingMedia => Set<ListingMedia>();
    public DbSet<ListingPriceHistory> ListingPriceHistory => Set<ListingPriceHistory>();
    public DbSet<ListingAttributeValue> ListingAttributeValues => Set<ListingAttributeValue>();
    public DbSet<ListingStatusHistory> ListingStatusHistory => Set<ListingStatusHistory>();
    public DbSet<ModerationCase> ModerationCases => Set<ModerationCase>();
    public DbSet<ModerationFinding> ModerationFindings => Set<ModerationFinding>();
    public DbSet<ModerationDecision> ModerationDecisions => Set<ModerationDecision>();
    public DbSet<ModerationAppeal> ModerationAppeals => Set<ModerationAppeal>();
    public DbSet<ListingLocation> ListingLocations => Set<ListingLocation>();
    public DbSet<Conversation> Conversations => Set<Conversation>();
    public DbSet<ChatMessage> ChatMessages => Set<ChatMessage>();
    public DbSet<ChatAttachment> ChatAttachments => Set<ChatAttachment>();
    public DbSet<ChatBlock> ChatBlocks => Set<ChatBlock>();
    public DbSet<ChatReport> ChatReports => Set<ChatReport>();
    public DbSet<ReplyTemplate> ReplyTemplates => Set<ReplyTemplate>();
    public DbSet<AutoReplySetting> AutoReplySettings => Set<AutoReplySetting>();
    public DbSet<Favorite> Favorites => Set<Favorite>();
    public DbSet<ComparisonItem> ComparisonItems => Set<ComparisonItem>();
    public DbSet<Deal> Deals => Set<Deal>();
    public DbSet<Review> Reviews => Set<Review>();
    public DbSet<UserNotification> UserNotifications => Set<UserNotification>();
    public DbSet<ListingViewEvent> ListingViewEvents => Set<ListingViewEvent>();
    public DbSet<SearchHistoryEntry> SearchHistoryEntries => Set<SearchHistoryEntry>();
    public DbSet<SavedSearch> SavedSearches => Set<SavedSearch>();
    public DbSet<FeatureFlag> FeatureFlags => Set<FeatureFlag>();
    public DbSet<BackgroundJobRun> BackgroundJobRuns => Set<BackgroundJobRun>();
    public DbSet<PlanDefinition> PlanDefinitions => Set<PlanDefinition>();
    public DbSet<Entitlement> Entitlements => Set<Entitlement>();
    public DbSet<PromotionProduct> PromotionProducts => Set<PromotionProduct>();
    public DbSet<PromoCode> PromoCodes => Set<PromoCode>();
    public DbSet<BonusLedgerEntry> BonusLedgerEntries => Set<BonusLedgerEntry>();
    public DbSet<PaymentTransaction> PaymentTransactions => Set<PaymentTransaction>();
    public DbSet<PromotionPurchase> PromotionPurchases => Set<PromotionPurchase>();
    public DbSet<RefundRequest> RefundRequests => Set<RefundRequest>();

    protected override void OnModelCreating(ModelBuilder builder)
    {
        base.OnModelCreating(builder);
        builder.HasPostgresExtension("pg_trgm");
        builder.Entity<ApplicationUser>().Property(x => x.DisplayName).HasMaxLength(80);
        builder.Entity<ApplicationUser>().Property(x => x.City).HasMaxLength(120);
        builder.Entity<ApplicationUser>().Property(x => x.Address).HasMaxLength(500);
        builder.Entity<ApplicationUser>().Property(x => x.CityLatitude).HasPrecision(9, 6);
        builder.Entity<ApplicationUser>().Property(x => x.CityLongitude).HasPrecision(9, 6);
        builder.Entity<ApplicationUser>().Property(x => x.AvatarUrl).HasMaxLength(500);
        builder.Entity<ApplicationUser>().Property(x => x.Bio).HasMaxLength(800);
        builder.Entity<UserSession>().HasIndex(x => new { x.UserId, x.RevokedAt });
        builder.Entity<UserSession>().Property(x => x.Device).HasMaxLength(240);
        builder.Entity<UserSession>().Property(x => x.IpAddress).HasMaxLength(64);
        builder.Entity<AuditEvent>().HasIndex(x => x.CreatedAt);
        builder.Entity<AuditEvent>().Property(x => x.EventType).HasMaxLength(80);
        builder.Entity<AuditEvent>().Property(x => x.Detail).HasMaxLength(600);
        builder.Entity<AuditEvent>().Property(x => x.IpAddress).HasMaxLength(64);
        builder.Entity<AuditEvent>().Property(x => x.ActorRole).HasMaxLength(80);
        builder.Entity<AuditEvent>().Property(x => x.EntityType).HasMaxLength(80);
        builder.Entity<AuditEvent>().Property(x => x.EntityId).HasMaxLength(120);
        builder.Entity<AuditEvent>().Property(x => x.OldValue).HasMaxLength(1000);
        builder.Entity<AuditEvent>().Property(x => x.NewValue).HasMaxLength(1000);
        builder.Entity<AuditEvent>().Property(x => x.Reason).HasMaxLength(1000);
        builder.Entity<AuditEvent>().Property(x => x.CorrelationId).HasMaxLength(80);
        builder.Entity<OneTimeCodeChallenge>().HasIndex(x => x.NormalizedEmail).IsUnique();
        builder.Entity<OneTimeCodeChallenge>().HasIndex(x => x.ExpiresAt);
        builder.Entity<OneTimeCodeChallenge>().Property(x => x.NormalizedEmail).HasMaxLength(320);
        builder.Entity<OneTimeCodeChallenge>().Property(x => x.CodeHash).HasMaxLength(32);
        builder.Entity<OneTimeCodeChallenge>().Property(x => x.Salt).HasMaxLength(16);
        builder.Entity<OneTimeCodeChallenge>().Property(x => x.DebugCode).HasMaxLength(6);
        builder.Entity<AuthRateLimitBucket>().HasKey(x => x.Key);
        builder.Entity<AuthRateLimitBucket>().Property(x => x.Key).HasMaxLength(64);
        builder.Entity<AuthRateLimitBucket>().HasIndex(x => x.ExpiresAt);
        builder.Entity<AccountErasureRequest>().HasIndex(x => x.UserId).IsUnique().HasFilter("\"Status\" = 'Pending'");
        builder.Entity<AccountErasureRequest>().HasIndex(x => new { x.Status, x.RequestedAt });
        builder.Entity<AccountErasureRequest>().Property(x => x.Status).HasMaxLength(24);
        builder.Entity<AccountErasureRequest>().Property(x => x.ResolutionNote).HasMaxLength(1000);
        builder.Entity<AccountErasureRequest>().HasOne(x => x.User).WithMany().HasForeignKey(x => x.UserId).OnDelete(DeleteBehavior.Restrict);
        builder.Entity<CatalogCategory>().HasIndex(x => x.Slug).IsUnique();
        builder.Entity<CatalogCategory>().Property(x => x.Slug).HasMaxLength(120);
        builder.Entity<CatalogCategory>().Property(x => x.Name).HasMaxLength(160);
        builder.Entity<CatalogCategory>().Property(x => x.Description).HasMaxLength(500);
        builder.Entity<CatalogCategory>().HasOne(x => x.Parent).WithMany(x => x.Children).HasForeignKey(x => x.ParentId).OnDelete(DeleteBehavior.Restrict);
        builder.Entity<CategorySchemaVersion>().HasIndex(x => new { x.CategoryId, x.Version }).IsUnique();
        builder.Entity<CategoryAttribute>().HasIndex(x => new { x.SchemaVersionId, x.Code }).IsUnique();
        builder.Entity<CategoryAttribute>().Property(x => x.Code).HasMaxLength(80);
        builder.Entity<CategoryAttribute>().Property(x => x.Name).HasMaxLength(160);
        builder.Entity<CategoryAttribute>().Property(x => x.DataType).HasMaxLength(32);
        builder.Entity<CategoryAttribute>().Property(x => x.Unit).HasMaxLength(40);
        builder.Entity<Listing>().Property(x => x.Title).HasMaxLength(160);
        builder.Entity<Listing>().Property(x => x.Description).HasMaxLength(5000);
        builder.Entity<Listing>().Property(x => x.DealType).HasMaxLength(32);
        builder.Entity<Listing>().Property(x => x.Condition).HasMaxLength(32);
        builder.Entity<Listing>().Property(x => x.Status).HasMaxLength(40);
        builder.Entity<Listing>().Property(x => x.Phone).HasMaxLength(32);
        builder.Entity<Listing>().HasIndex(x => new { x.OwnerId, x.Status });
        builder.Entity<ListingRevision>().HasIndex(x => new { x.ListingId, x.RevisionNumber }).IsUnique();
        builder.Entity<ListingMedia>().Property(x => x.Url).HasMaxLength(500);
        builder.Entity<ListingMedia>().Property(x => x.Alt).HasMaxLength(200);
        builder.Entity<ListingAttributeValue>().HasIndex(x => new { x.ListingId, x.AttributeCode }).IsUnique();
        builder.Entity<ListingAttributeValue>().Property(x => x.AttributeCode).HasMaxLength(80);
        builder.Entity<ListingStatusHistory>().Property(x => x.Status).HasMaxLength(40);
        builder.Entity<ModerationCase>().HasIndex(x => new { x.Status, x.RiskLevel, x.CreatedAt });
        builder.Entity<ModerationCase>().Property(x => x.Status).HasMaxLength(32); builder.Entity<ModerationCase>().Property(x => x.RiskLevel).HasMaxLength(16); builder.Entity<ModerationCase>().Property(x => x.RuleSetVersion).HasMaxLength(40);
        builder.Entity<ModerationFinding>().Property(x => x.Code).HasMaxLength(80); builder.Entity<ModerationFinding>().Property(x => x.RiskCategory).HasMaxLength(32); builder.Entity<ModerationFinding>().Property(x => x.RuleCode).HasMaxLength(80); builder.Entity<ModerationFinding>().Property(x => x.RuleVersion).HasMaxLength(40); builder.Entity<ModerationFinding>().Property(x => x.Fragment).HasMaxLength(500); builder.Entity<ModerationFinding>().Property(x => x.RecommendedAction).HasMaxLength(500); builder.Entity<ModerationFinding>().Property(x => x.Evidence).HasMaxLength(1000);
        builder.Entity<ModerationDecision>().Property(x => x.Action).HasMaxLength(40); builder.Entity<ModerationDecision>().Property(x => x.Reason).HasMaxLength(1000); builder.Entity<ModerationDecision>().Property(x => x.ProblemField).HasMaxLength(120); builder.Entity<ModerationDecision>().Property(x => x.RuleReference).HasMaxLength(300); builder.Entity<ModerationDecision>().Property(x => x.CorrectionInstruction).HasMaxLength(1000);
        builder.Entity<ModerationAppeal>().Property(x => x.Message).HasMaxLength(2000); builder.Entity<ModerationAppeal>().Property(x => x.Status).HasMaxLength(32);
        builder.Entity<ListingLocation>().HasIndex(x => x.ListingId).IsUnique();
        builder.Entity<ListingLocation>().Property(x => x.City).HasMaxLength(120);
        builder.Entity<ListingLocation>().Property(x => x.District).HasMaxLength(160);
        builder.Entity<ListingLocation>().Property(x => x.ExactAddress).HasMaxLength(500);
        builder.Entity<ListingLocation>().HasOne(x => x.Listing).WithOne(x => x.Location).HasForeignKey<ListingLocation>(x => x.ListingId).OnDelete(DeleteBehavior.Cascade);
        builder.Entity<Conversation>().HasIndex(x => new { x.ListingId, x.BuyerId }).IsUnique();
        builder.Entity<Conversation>().HasOne(x => x.Seller).WithMany().HasForeignKey(x => x.SellerId).OnDelete(DeleteBehavior.Restrict);
        builder.Entity<Conversation>().HasOne(x => x.Buyer).WithMany().HasForeignKey(x => x.BuyerId).OnDelete(DeleteBehavior.Restrict);
        builder.Entity<ChatMessage>().HasIndex(x => new { x.ConversationId, x.CreatedAt }); builder.Entity<ChatMessage>().Property(x => x.Kind).HasMaxLength(24); builder.Entity<ChatMessage>().Property(x => x.Text).HasMaxLength(5000);
        builder.Entity<ChatMessage>().HasOne(x => x.Sender).WithMany().HasForeignKey(x => x.SenderId).OnDelete(DeleteBehavior.Restrict);
        builder.Entity<ChatAttachment>().Property(x => x.OriginalName).HasMaxLength(240); builder.Entity<ChatAttachment>().Property(x => x.StorageKey).HasMaxLength(500); builder.Entity<ChatAttachment>().Property(x => x.MimeType).HasMaxLength(120); builder.Entity<ChatAttachment>().Property(x => x.SafetyStatus).HasMaxLength(24);
        builder.Entity<ChatBlock>().HasIndex(x => new { x.ConversationId, x.BlockerId, x.BlockedId }).IsUnique();
        builder.Entity<ChatReport>().Property(x => x.Reason).HasMaxLength(1000);
        builder.Entity<ReplyTemplate>().Property(x => x.Title).HasMaxLength(100); builder.Entity<ReplyTemplate>().Property(x => x.Text).HasMaxLength(2000);
        builder.Entity<AutoReplySetting>().HasIndex(x => new { x.OwnerId, x.ListingId }).IsUnique(); builder.Entity<AutoReplySetting>().Property(x => x.Text).HasMaxLength(2000);
        builder.Entity<Favorite>().HasIndex(x => new { x.UserId, x.ListingId }).IsUnique();
        builder.Entity<ComparisonItem>().HasIndex(x => new { x.UserId, x.ListingId }).IsUnique();
        builder.Entity<Deal>().HasIndex(x => x.ConversationId).IsUnique(); builder.Entity<Deal>().Property(x => x.Status).HasMaxLength(32);
        builder.Entity<Review>().HasIndex(x => new { x.DealId, x.AuthorId }).IsUnique(); builder.Entity<Review>().Property(x => x.Text).HasMaxLength(2000); builder.Entity<Review>().ToTable(x => x.HasCheckConstraint("CK_Reviews_Rating", "\"Rating\" >= 1 AND \"Rating\" <= 5"));
        builder.Entity<UserNotification>().HasIndex(x => new { x.UserId, x.ReadAt, x.CreatedAt }); builder.Entity<UserNotification>().Property(x => x.Type).HasMaxLength(40); builder.Entity<UserNotification>().Property(x => x.Text).HasMaxLength(500); builder.Entity<UserNotification>().Property(x => x.Link).HasMaxLength(500);
        builder.Entity<ListingViewEvent>().HasIndex(x => new { x.UserId, x.ListingId }).IsUnique();
        builder.Entity<ListingViewEvent>().HasIndex(x => new { x.UserId, x.ViewedAt });
        builder.Entity<SearchHistoryEntry>().HasIndex(x => new { x.UserId, x.Fingerprint }).IsUnique();
        builder.Entity<SearchHistoryEntry>().HasIndex(x => new { x.UserId, x.SearchedAt });
        builder.Entity<SearchHistoryEntry>().Property(x => x.Fingerprint).HasMaxLength(64);
        builder.Entity<SearchHistoryEntry>().Property(x => x.Label).HasMaxLength(240);
        builder.Entity<SearchHistoryEntry>().Property(x => x.QueryString).HasMaxLength(2000);
        builder.Entity<SavedSearch>().HasIndex(x => new { x.UserId, x.Fingerprint }).IsUnique();
        builder.Entity<SavedSearch>().Property(x => x.Fingerprint).HasMaxLength(64);
        builder.Entity<SavedSearch>().Property(x => x.Name).HasMaxLength(120);
        builder.Entity<SavedSearch>().Property(x => x.QueryString).HasMaxLength(2000);
        builder.Entity<FeatureFlag>().HasIndex(x => x.Key).IsUnique();
        builder.Entity<FeatureFlag>().Property(x => x.Key).HasMaxLength(120);
        builder.Entity<FeatureFlag>().Property(x => x.Description).HasMaxLength(500);
        builder.Entity<BackgroundJobRun>().HasIndex(x => new { x.JobName, x.StartedAt });
        builder.Entity<BackgroundJobRun>().Property(x => x.JobName).HasMaxLength(120);
        builder.Entity<BackgroundJobRun>().Property(x => x.Status).HasMaxLength(32);
        builder.Entity<BackgroundJobRun>().Property(x => x.Detail).HasMaxLength(1000);
        builder.Entity<BackgroundJobRun>().HasIndex(x => new { x.Status, x.AvailableAt });
        builder.Entity<PlanDefinition>().HasIndex(x => new { x.Code, x.Version }).IsUnique(); builder.Entity<PlanDefinition>().Property(x => x.Code).HasMaxLength(80); builder.Entity<PlanDefinition>().Property(x => x.Name).HasMaxLength(120);
        builder.Entity<Entitlement>().HasIndex(x => new { x.UserId, x.EndsAt }); builder.Entity<Entitlement>().Property(x => x.PlanCode).HasMaxLength(80);
        builder.Entity<PromotionProduct>().HasIndex(x => new { x.Code, x.PriceVersion }).IsUnique(); builder.Entity<PromotionProduct>().Property(x => x.Code).HasMaxLength(80); builder.Entity<PromotionProduct>().Property(x => x.Name).HasMaxLength(120); builder.Entity<PromotionProduct>().Property(x => x.Description).HasMaxLength(500);
        builder.Entity<PromoCode>().HasIndex(x => x.Code).IsUnique(); builder.Entity<PromoCode>().Property(x => x.Code).HasMaxLength(60); builder.Entity<PromoCode>().ToTable(x => x.HasCheckConstraint("CK_PromoCodes_Discount", "\"DiscountPercent\" >= 0 AND \"DiscountPercent\" <= 100"));
        builder.Entity<BonusLedgerEntry>().HasIndex(x => new { x.UserId, x.CreatedAt }); builder.Entity<BonusLedgerEntry>().Property(x => x.Reason).HasMaxLength(500);
        builder.Entity<PaymentTransaction>().HasIndex(x => new { x.UserId, x.IdempotencyKey }).IsUnique(); builder.Entity<PaymentTransaction>().Property(x => x.IdempotencyKey).HasMaxLength(100); builder.Entity<PaymentTransaction>().Property(x => x.Kind).HasMaxLength(32); builder.Entity<PaymentTransaction>().Property(x => x.ProductType).HasMaxLength(40); builder.Entity<PaymentTransaction>().Property(x => x.ProductCode).HasMaxLength(80); builder.Entity<PaymentTransaction>().Property(x => x.Status).HasMaxLength(32);
        builder.Entity<PromotionPurchase>().HasIndex(x => new { x.ListingId, x.Status }); builder.Entity<PromotionPurchase>().Property(x => x.ProductCode).HasMaxLength(80); builder.Entity<PromotionPurchase>().Property(x => x.Status).HasMaxLength(32);
        builder.Entity<RefundRequest>().HasIndex(x => x.PaymentId).IsUnique(); builder.Entity<RefundRequest>().Property(x => x.Reason).HasMaxLength(1000); builder.Entity<RefundRequest>().Property(x => x.Status).HasMaxLength(32); builder.Entity<RefundRequest>().Property(x => x.ResolutionNote).HasMaxLength(1000);
    }
}
