using Marketplace.Web.Modules.Listings;

namespace Marketplace.Web.Modules.Monetization;

public sealed class PlanDefinition { public Guid Id { get; set; } public string Code { get; set; } = string.Empty; public string Name { get; set; } = string.Empty; public int Version { get; set; } = 1; public decimal MonthlyPrice { get; set; } public decimal AnnualPrice { get; set; } public int ActiveListingLimit { get; set; } = 10; public bool IsActive { get; set; } = true; }
public sealed class Entitlement { public Guid Id { get; set; } public Guid UserId { get; set; } public string PlanCode { get; set; } = "free"; public int ActiveListingLimit { get; set; } = 10; public DateTimeOffset StartsAt { get; set; } = DateTimeOffset.UtcNow; public DateTimeOffset? EndsAt { get; set; } }
public sealed class PromotionProduct { public Guid Id { get; set; } public string Code { get; set; } = string.Empty; public string Name { get; set; } = string.Empty; public string Description { get; set; } = string.Empty; public int PriceVersion { get; set; } = 1; public decimal Price { get; set; } public int DurationDays { get; set; } public bool IsActive { get; set; } = true; }
public sealed class PromoCode { public Guid Id { get; set; } public string Code { get; set; } = string.Empty; public int DiscountPercent { get; set; } public decimal BonusAmount { get; set; } public int MaxUses { get; set; } public int UsedCount { get; set; } public bool IsActive { get; set; } = true; public DateTimeOffset? ExpiresAt { get; set; } }
public sealed class BonusLedgerEntry { public Guid Id { get; set; } public Guid UserId { get; set; } public decimal Amount { get; set; } public string Reason { get; set; } = string.Empty; public Guid? PaymentId { get; set; } public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow; public DateTimeOffset? ExpiresAt { get; set; } }
public sealed class PaymentTransaction { public Guid Id { get; set; } public Guid UserId { get; set; } public string IdempotencyKey { get; set; } = string.Empty; public string Kind { get; set; } = "Purchase"; public string ProductType { get; set; } = string.Empty; public string ProductCode { get; set; } = string.Empty; public Guid? ListingId { get; set; } public decimal GrossAmount { get; set; } public decimal DiscountAmount { get; set; } public decimal BonusUsed { get; set; } public decimal CashAmount { get; set; } public string Status { get; set; } = "Succeeded"; public Guid? ParentPaymentId { get; set; } public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow; }
public sealed class PromotionPurchase { public Guid Id { get; set; } public Guid UserId { get; set; } public Guid ListingId { get; set; } public Listing Listing { get; set; } = null!; public string ProductCode { get; set; } = string.Empty; public Guid PaymentId { get; set; } public DateTimeOffset StartsAt { get; set; } = DateTimeOffset.UtcNow; public DateTimeOffset EndsAt { get; set; } public string Status { get; set; } = "Active"; }
public sealed class RefundRequest { public Guid Id { get; set; } public Guid PaymentId { get; set; } public Guid RequestedById { get; set; } public string Reason { get; set; } = string.Empty; public string Status { get; set; } = "Pending"; public Guid? ResolvedById { get; set; } public string? ResolutionNote { get; set; } public DateTimeOffset RequestedAt { get; set; } = DateTimeOffset.UtcNow; public DateTimeOffset? ResolvedAt { get; set; } }
